apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cr
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cr
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80